### PR TITLE
First draft of documentation on a debian 9.2 setup

### PR DESCRIPTION
**Pull request by danfossi**

### CODE REVIEW

**Comment by serhack** [comment]
Seems good! Thanks

**Comment by danfossi** [comment]
Hi @Serhack,
I love this project, I am proud to to contribute and I hope to see it grow!
________________________________
Da: serhack <notifications@github.com>
Inviato: giovedì 16 novembre 2017 18:59
A: annularis/shop
Cc: Dennis; Author
Oggetto: Re: [annularis/shop] First draft of documentation on a debian 9.2 setup (#4)


Seems good! Thanks

**Comment by serhack** [comment]
I'd like to talk with you. Are you italian? Have you got any contact?

**Comment by danfossi** [comment]
Hi @serhack,
yes, I'm an Italian guy (sorry for my poor English!)

You can write me at: danfossi [at] outlook [dot] com

Cheers,
Dennis



Da: serhack
Inviato: venerdì 17 novembre, 14:28
Oggetto: Re: [annularis/shop] First draft of documentation on a debian 9.2 setup (#4)
A: annularis/shop
Cc: Dennis, Author


I'd like to talk with you. Are you italian? Have you got any contact?

**Comment by serhack** [comment]
Me too. You can send me a mail support at monerointegrations dot com

**Pull request merged**
